In [42]:
import tensorflow
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [43]:
dados = pd.read_csv('../dados/dados_tratado.csv')

In [44]:
dados.head()

age  sex  height  weight  qrs_duration  p_r_interval  q_t_interval  \
0   75    0     190      80            91           193           371   
1   56    1     165      64            81           174           401   
2   54    0     172      95           138           163           386   
3   55    0     175      94           100           202           380   
4   13    0     169      51           100           167           321   

   t_interval  p_interval  qrs   T   P  QRST  heart_rate  q_wave  r_wave  \
0         174         121  -16  13  64    -2          63       0      52   
1         149          39   25  37 -17    31          53       0      48   
2         185         102   96  34  70    66          75       0      40   
3         179         143   28  11  -5    20          71       0      72   
4         174          91  107  66  52    88          84       0      36   

   s_wave  R_wave  S_wave  diagnosis  
0      44       0       0          8  
1       0       0       0          6  
2      80       0       0         10  
3      20       0       0          1  
4      48       0       0         14

In [45]:
x = dados[['age', 'sex', 'height', 'weight', 'qrs_duration', 'p_r_interval', 'q_t_interval', 't_interval', 'p_interval',
          'qrs', 'T', 'P', 'QRST', 'heart_rate', 'q_wave', 'r_wave', 's_wave', 'R_wave', 'S_wave']]
y = dados['diagnosis']

In [ ]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size= 0.25, stratify=y)
scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

In [46]:
treino_x

array([[-0.61123014, -1.1622161 ,  0.73202498, ..., -0.02139924,
        -0.05643326,  0.        ],
       [-1.03787227, -1.1622161 ,  0.25666147, ...,  0.59139716,
        -0.05643326,  0.        ],
       [-1.28166776,  0.86042518, -0.10900277, ...,  0.59139716,
        -0.05643326,  0.        ],
       ...,
       [-0.85502564,  0.86042518, -0.03586992, ..., -1.04272657,
        -0.05643326,  0.        ],
       [ 0.42490073, -1.1622161 ,  0.1469622 , ...,  0.18286623,
        17.72004515,  0.        ],
       [-0.12363915, -1.1622161 ,  0.47606001, ..., -1.04272657,
        -0.05643326,  0.        ]])

In [47]:
tensor_treino_x = tensorflow.convert_to_tensor(treino_x)
tensor_teste_x = tensorflow.convert_to_tensor(teste_x)
tensor_treino_y = tensorflow.convert_to_tensor(treino_y)
tensor_teste_y = tensorflow.convert_to_tensor(teste_y)

In [48]:
tensor_treino_x

<tf.Tensor: shape=(315, 19), dtype=float64, numpy=
array([[-0.61123014, -1.1622161 ,  0.73202498, ..., -0.02139924,
        -0.05643326,  0.        ],
       [-1.03787227, -1.1622161 ,  0.25666147, ...,  0.59139716,
        -0.05643326,  0.        ],
       [-1.28166776,  0.86042518, -0.10900277, ...,  0.59139716,
        -0.05643326,  0.        ],
       ...,
       [-0.85502564,  0.86042518, -0.03586992, ..., -1.04272657,
        -0.05643326,  0.        ],
       [ 0.42490073, -1.1622161 ,  0.1469622 , ...,  0.18286623,
        17.72004515,  0.        ],
       [-0.12363915, -1.1622161 ,  0.47606001, ..., -1.04272657,
        -0.05643326,  0.        ]])>

In [49]:
normalizer = tensorflow.keras.layers.Normalization(axis=-1)
normalizer.adapt(tensor_treino_x)

In [50]:
# camadas
model = keras.Sequential([
    normalizer,
    keras.layers.Dense(340, activation=tensorflow.nn.relu),
    keras.layers.Dense(170, activation=tensorflow.nn.relu),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(170, activation=tensorflow.nn.relu),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(17, activation=tensorflow.nn.softmax)
                         ])


In [51]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [53]:
model.fit(tensor_treino_x, tensor_treino_y, epochs=10, validation_split=0.2)

Epoch 1/10
8/8 [==============================] - 0s 8ms/step - loss: 0.8228 - accuracy: 0.7302 - val_loss: 1.2748 - val_accuracy: 0.6508
Epoch 2/10
8/8 [==============================] - 0s 6ms/step - loss: 0.7864 - accuracy: 0.7302 - val_loss: 1.2773 - val_accuracy: 0.6190
Epoch 3/10
8/8 [==============================] - 0s 5ms/step - loss: 0.7452 - accuracy: 0.7540 - val_loss: 1.2980 - val_accuracy: 0.6032
Epoch 4/10
8/8 [==============================] - 0s 5ms/step - loss: 0.6889 - accuracy: 0.7937 - val_loss: 1.3044 - val_accuracy: 0.6825
Epoch 5/10
8/8 [==============================] - 0s 5ms/step - loss: 0.6239 - accuracy: 0.7698 - val_loss: 1.2757 - val_accuracy: 0.6190
Epoch 6/10
8/8 [==============================] - 0s 5ms/step - loss: 0.5651 - accuracy: 0.8135 - val_loss: 1.2706 - val_accuracy: 0.6667
Epoch 7/10
8/8 [==============================] - 0s 5ms/step - loss: 0.5176 - accuracy: 0.8056 - val_loss: 1.3066 - val_accuracy: 0.6508
Epoch 8/10
8/8 [==================

In [20]:
tensor_teste_y

<tf.Tensor: shape=(105,), dtype=int64, numpy=
array([ 1,  5,  4, 16,  2,  1,  1,  3,  6,  6,  1,  4,  1,  1,  4,  1, 10,
        1, 16,  6,  6,  1,  1,  1,  1,  1,  2,  5,  2,  1,  1, 10, 10,  2,
       10,  1,  7, 10, 10,  1,  2, 16,  3,  9,  1,  3,  1,  1,  1,  1,  1,
        1,  1,  2,  1,  1,  1, 10, 16,  2,  1,  1,  2,  1,  1,  4, 10, 10,
        1,  1,  1,  2,  1, 16, 10,  1,  6,  1,  1,  1, 10,  1,  1,  1,  1,
        1,  1,  1, 10,  1,  1,  1,  6,  1,  1,  1,  1,  1,  1,  1,  1,  9,
       14,  1,  5], dtype=int64)>

In [21]:
previsoes = model.predict(tensor_teste_x)

4/4 [==============================] - 0s 1ms/step


In [22]:
previsoes_lista = [np.argmax(previsao) for previsao in previsoes]

In [54]:
loss_test, accuracy_test = model.evaluate(tensor_teste_x, tensor_teste_y)
print(f'perda teste: {loss_test}')
print(f'Acurácia teste: {accuracy_test}')

4/4 [==============================] - 0s 2ms/step - loss: 1.4079 - accuracy: 0.6571
perda teste: 1.407938003540039
Acurácia teste: 0.6571428775787354
